[package]
name = "inseam-wasm-host"
version.workspace = true
edition.workspace = true

[dependencies]
inseam-kernel.workspace = true
inseam-seams.workspace = true

async-trait.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
wasmtime.workspace = true

[dev-dependencies]
anyhow.workspace = true
tempfile.workspace = true
tokio = { workspace = true }
