//! Repo automation (`cargo xtask <command>`). Not part of any distribution.
//!
//! `docs` regenerates the source-exported pages under `docs/` — crate
//! overviews from each crate's `//!` block, the WIT contract via
//! wit-bindgen's markdown backend, and skill pages from `skills/*/SKILL.md`
//! — so the prose docs tree stays the single serialization the doc site
//! consumes (`docs/architecture/doc-generation.md`).
//!
//! `release` is the operator half of `design/releases.md`: `keygen` makes
//! the signing keypair, `promote <tag>` signs a manifest for a CI-built
//! draft release and publishes it.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

mod release;

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let root = repo_root()?;
    match args.first().map(String::as_str) {
        Some("docs") => docs(&root),
        Some("release") => release::run(&args[1..]),
        _ => bail!("usage: cargo xtask docs | cargo xtask release <keygen|promote>"),
    }
}

/// The workspace root: the manifest dir's parent (`xtask/` lives at the root).
fn repo_root() -> Result<PathBuf> {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .map(Path::to_path_buf)
        .context("xtask manifest dir has no parent")
}

fn docs(root: &Path) -> Result<()> {
    crate_pages(root)?;
    wit_pages(root)?;
    skill_pages(root)?;
    Ok(())
}

fn generated_header(source: &str) -> String {
    format!(
        "<!-- GENERATED by `cargo xtask docs` from `{source}` — edit the source, not this file. -->\n\n"
    )
}

fn write_page(path: &Path, contents: &str) -> Result<()> {
    if let Some(dir) = path.parent() {
        fs::create_dir_all(dir)?;
    }
    fs::write(path, contents).with_context(|| format!("writing {}", path.display()))?;
    println!("wrote {}", path.display());
    Ok(())
}

/// One page per workspace crate under `docs/crates/`, from the leading `//!`
/// block of its `lib.rs` (or `main.rs` for binaries).
fn crate_pages(root: &Path) -> Result<()> {
    for member in workspace_members(root)? {
        let crate_dir = root.join(&member);
        let name = member
            .rsplit('/')
            .next()
            .expect("rsplit yields at least one element");
        if name == "xtask" {
            continue;
        }
        let source = ["src/lib.rs", "src/main.rs"]
            .iter()
            .map(|rel| crate_dir.join(rel))
            .find(|p| p.exists())
            .with_context(|| format!("{member}: no src/lib.rs or src/main.rs"))?;
        let text = fs::read_to_string(&source)?;
        let body = crate_doc_block(&text)
            .with_context(|| format!("{member}: no leading //! doc block"))?;
        let rel_source = source
            .strip_prefix(root)
            .expect("source is under the repo root");
        let page = format!(
            "{}# {name}\n\n{body}\n",
            generated_header(&rel_source.display().to_string()),
        );
        write_page(&root.join("docs/crates").join(format!("{name}.md")), &page)?;
    }
    Ok(())
}

fn workspace_members(root: &Path) -> Result<Vec<String>> {
    let manifest: toml::Table = fs::read_to_string(root.join("Cargo.toml"))?.parse()?;
    let members = manifest
        .get("workspace")
        .and_then(|w| w.get("members"))
        .and_then(|m| m.as_array())
        .context("no [workspace] members in root Cargo.toml")?;
    Ok(members
        .iter()
        .filter_map(|m| m.as_str())
        .map(str::to_owned)
        .collect())
}

/// The contiguous leading `//!` block, stripped of comment markers.
fn crate_doc_block(source: &str) -> Option<String> {
    let lines: Vec<&str> = source
        .lines()
        .take_while(|l| l.starts_with("//!"))
        .map(|l| {
            l.strip_prefix("//! ")
                .unwrap_or(l.strip_prefix("//!").unwrap_or(l))
        })
        .collect();
    if lines.is_empty() {
        return None;
    }
    Some(lines.join("\n"))
}

/// The WIT contract rendered by wit-bindgen's markdown backend, one page per
/// world, under `docs/plugins/`.
fn wit_pages(root: &Path) -> Result<()> {
    use wit_bindgen_core::wit_parser::Resolve;

    let wit_dir = root.join("crates/inseam-wasm-host/wit");
    let mut resolve = Resolve::default();
    let (pkg, _) = resolve
        .push_path(&wit_dir)
        .with_context(|| format!("parsing {}", wit_dir.display()))?;
    let world = resolve.select_world(&[pkg], None)?;

    let mut files = wit_bindgen_core::Files::default();
    let opts = wit_bindgen_markdown::Opts::default();
    opts.build().generate(&resolve, world, &mut files)?;

    for (name, contents) in files.iter() {
        if !name.ends_with(".md") {
            continue;
        }
        let stem = name.trim_end_matches(".md");
        let page = format!(
            "{}{}",
            generated_header("crates/inseam-wasm-host/wit"),
            retitle_world(&String::from_utf8_lossy(contents), stem),
        );
        write_page(
            &root.join("docs/plugins").join(format!("{stem}-wit.md")),
            &page,
        )?;
    }
    Ok(())
}

/// Replaces wit-bindgen's page title — `# <a id="…"></a>World <name>` — with a
/// plain heading. The doc site lifts each page's `# ` line into the Starlight
/// frontmatter title, where the raw anchor would show up verbatim. Anchors
/// further down the page stay: the type cross-links point at them.
fn retitle_world(rendered: &str, world: &str) -> String {
    let body = rendered
        .strip_prefix("# ")
        .and_then(|rest| rest.split_once('\n'))
        .map_or(rendered, |(_, body)| body);
    format!("# WIT world: {world}\n\n{}", body.trim_start_matches('\n'))
}

/// One page per skill under `docs/skills/`, from `skills/*/SKILL.md` with the
/// frontmatter folded into a title and byline.
fn skill_pages(root: &Path) -> Result<()> {
    let skills_dir = root.join("skills");
    for entry in fs::read_dir(&skills_dir)? {
        let skill_md = entry?.path().join("SKILL.md");
        if !skill_md.exists() {
            continue;
        }
        let text = fs::read_to_string(&skill_md)?;
        let rel_source = skill_md
            .strip_prefix(root)
            .expect("skill lives under the repo root");
        let (front, body) = split_frontmatter(&text)
            .with_context(|| format!("{}: no frontmatter", skill_md.display()))?;
        let front: toml_frontmatter::Frontmatter = front.parse()?;
        let page = format!(
            "{}# Skill: {}\n\n> {}\n{}",
            generated_header(&rel_source.display().to_string()),
            front.name,
            front.description,
            demote_headings(body),
        );
        write_page(
            &root.join("docs/skills").join(format!("{}.md", front.name)),
            &page,
        )?;
    }
    Ok(())
}

/// Pushes every ATX heading down one level so the page keeps a single `#`
/// title. Fenced code blocks are left alone.
fn demote_headings(body: &str) -> String {
    let mut in_fence = false;
    let mut out = String::with_capacity(body.len());
    for line in body.lines() {
        if line.trim_start().starts_with("```") {
            in_fence = !in_fence;
        }
        if !in_fence && line.starts_with('#') {
            out.push('#');
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// Splits `---\n<yaml>\n---\n<body>`; returns (frontmatter, body).
fn split_frontmatter(text: &str) -> Option<(&str, &str)> {
    let rest = text.strip_prefix("---\n")?;
    let end = rest.find("\n---\n")?;
    Some((&rest[..end], &rest[end + "\n---\n".len()..]))
}

mod toml_frontmatter {
    //! Minimal parse of the two SKILL.md frontmatter keys we render. The
    //! frontmatter is YAML, but `name:`/`description:` single-line scalars
    //! read fine without a YAML dependency.
    use std::str::FromStr;

    use anyhow::{Context, Result};

    pub struct Frontmatter {
        pub name: String,
        pub description: String,
    }

    impl FromStr for Frontmatter {
        type Err = anyhow::Error;

        fn from_str(s: &str) -> Result<Self> {
            let field = |key: &str| -> Result<String> {
                s.lines()
                    .find_map(|l| l.strip_prefix(&format!("{key}:")))
                    .map(|v| v.trim().to_owned())
                    .with_context(|| format!("frontmatter missing `{key}:`"))
            };
            Ok(Frontmatter {
                name: field("name")?,
                description: field("description")?,
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_leading_doc_block() {
        let src = "//! First line.\n//!\n//! Second para.\nuse std::fs;\n";
        assert_eq!(
            crate_doc_block(src).as_deref(),
            Some("First line.\n\nSecond para.")
        );
    }

    #[test]
    fn rejects_source_without_doc_block() {
        assert_eq!(crate_doc_block("use std::fs;\n"), None);
    }

    #[test]
    fn replaces_anchored_world_title() {
        let rendered =
            "# <a id=\"transform_plugin\"></a>World transform-plugin\n\n\n\n - Imports:\n";
        assert_eq!(
            retitle_world(rendered, "transform-plugin"),
            "# WIT world: transform-plugin\n\n - Imports:\n"
        );
    }

    #[test]
    fn keeps_anchors_below_the_title() {
        let rendered = "# <a id=\"w\"></a>World w\n\n## <a id=\"log\"></a>`log: func`\n";
        assert!(retitle_world(rendered, "w").contains("<a id=\"log\"></a>"));
    }

    #[test]
    fn splits_frontmatter_from_body() {
        let text = "---\nname: x\n---\nbody\n";
        assert_eq!(split_frontmatter(text), Some(("name: x", "body\n")));
    }
}
